name: Bug report
description: Report a reproducible bug
title: "[Bug]: "
labels:
  - bug
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting this issue.
        Please provide enough detail so maintainers can reproduce it quickly.
  - type: input
    id: summary
    attributes:
      label: Summary
      description: Short description of the bug
      placeholder: Exported HTML breaks in Outlook...
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: List exact steps
      placeholder: |
        1. Go to ...
        2. Click ...
        3. Observe ...
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      placeholder: The preview should...
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
      placeholder: Instead, it...
    validations:
      required: true
  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Browser, OS, Node version, app version/commit
      placeholder: Chrome 122, Windows 11, Node 22...
    validations:
      required: true
  - type: textarea
    id: extra
    attributes:
      label: Additional context
      description: Screenshots, logs, MJML sample, etc.
