name: Feature request
description: Suggest an improvement
title: "[Feature]: "
labels:
  - enhancement
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting an improvement.
        Please focus on the problem and expected user impact.
  - type: textarea
    id: problem
    attributes:
      label: Problem statement
      description: What problem are you trying to solve?
      placeholder: As a user, I cannot...
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
      description: Describe the feature you want
      placeholder: Add a block that...
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Any workaround or alternative solution?
  - type: textarea
    id: impact
    attributes:
      label: Impact
      description: Who benefits and how?
      placeholder: Improves conversion for...
    validations:
      required: true
